export * from './lib/autogestion-login/autogestion-login.component';
export * from './lib/autogestion-registro/autogestion-registro.component';
export * from './lib/autogestion-shell/autogestion-shell.component';
export * from './lib/mi-hogar/mi-hogar.component';
export * from './lib/mi-perfil/mi-perfil.component';
export * from './lib/mi-educacion/mi-educacion.component';
export * from './lib/mi-economia/mi-economia.component';
export * from './lib/mi-salud/mi-salud.component';
export * from './lib/mi-constancia/mi-constancia.component';
